name: otoddyota
description: Simple, drop-in Over-The-Air (OTA) code push client for Flutter applications with automatic engine patch detection.
version: 1.0.0
homepage: https://github.com/MohitMakhijani/otoddy_ota_inhouse
repository: https://github.com/MohitMakhijani/otoddy_ota_inhouse
issue_tracker: https://github.com/MohitMakhijani/otoddy_ota_inhouse/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
